// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: note.proto

package note

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// NoteServiceService defines service.
type NoteServiceService interface {
	// CreateNote 创建笔记
	CreateNote(ctx context.Context, req *CreateNoteRequest) (*CreateNoteResponse, error)
	// GetNote 查询单条笔记（走 Cache Aside：Redis -> MongoDB）
	GetNote(ctx context.Context, req *GetNoteRequest) (*GetNoteResponse, error)
	// ListNotes 查询用户笔记列表（直查 MongoDB，依赖 user_id+created_at 复合索引）
	ListNotes(ctx context.Context, req *ListNotesRequest) (*ListNotesResponse, error)
	// DeleteNote 删除笔记（先删 Mongo 再 Del Redis 缓存）
	DeleteNote(ctx context.Context, req *DeleteNoteRequest) (*DeleteNoteResponse, error)
}

func NoteServiceService_CreateNote_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateNoteRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(NoteServiceService).CreateNote(ctx, reqbody.(*CreateNoteRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func NoteServiceService_GetNote_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetNoteRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(NoteServiceService).GetNote(ctx, reqbody.(*GetNoteRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func NoteServiceService_ListNotes_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListNotesRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(NoteServiceService).ListNotes(ctx, reqbody.(*ListNotesRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func NoteServiceService_DeleteNote_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeleteNoteRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(NoteServiceService).DeleteNote(ctx, reqbody.(*DeleteNoteRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// NoteServiceServer_ServiceDesc descriptor for server.RegisterService.
var NoteServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.demo.note.NoteService",
	HandlerType: ((*NoteServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.demo.note.NoteService/CreateNote",
			Func: NoteServiceService_CreateNote_Handler,
		},
		{
			Name: "/trpc.demo.note.NoteService/GetNote",
			Func: NoteServiceService_GetNote_Handler,
		},
		{
			Name: "/trpc.demo.note.NoteService/ListNotes",
			Func: NoteServiceService_ListNotes_Handler,
		},
		{
			Name: "/trpc.demo.note.NoteService/DeleteNote",
			Func: NoteServiceService_DeleteNote_Handler,
		},
	},
}

// RegisterNoteServiceService registers service.
func RegisterNoteServiceService(s server.Service, svr NoteServiceService) {
	if err := s.Register(&NoteServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("NoteService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedNoteService struct{}

// CreateNote 创建笔记
func (s *UnimplementedNoteService) CreateNote(ctx context.Context, req *CreateNoteRequest) (*CreateNoteResponse, error) {
	return nil, errors.New("rpc CreateNote of service NoteService is not implemented")
}

// GetNote 查询单条笔记（走 Cache Aside：Redis -> MongoDB）
func (s *UnimplementedNoteService) GetNote(ctx context.Context, req *GetNoteRequest) (*GetNoteResponse, error) {
	return nil, errors.New("rpc GetNote of service NoteService is not implemented")
}

// ListNotes 查询用户笔记列表（直查 MongoDB，依赖 user_id+created_at 复合索引）
func (s *UnimplementedNoteService) ListNotes(ctx context.Context, req *ListNotesRequest) (*ListNotesResponse, error) {
	return nil, errors.New("rpc ListNotes of service NoteService is not implemented")
}

// DeleteNote 删除笔记（先删 Mongo 再 Del Redis 缓存）
func (s *UnimplementedNoteService) DeleteNote(ctx context.Context, req *DeleteNoteRequest) (*DeleteNoteResponse, error) {
	return nil, errors.New("rpc DeleteNote of service NoteService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// NoteServiceClientProxy defines service client proxy
type NoteServiceClientProxy interface {
	// CreateNote 创建笔记
	CreateNote(ctx context.Context, req *CreateNoteRequest, opts ...client.Option) (rsp *CreateNoteResponse, err error)
	// GetNote 查询单条笔记（走 Cache Aside：Redis -> MongoDB）
	GetNote(ctx context.Context, req *GetNoteRequest, opts ...client.Option) (rsp *GetNoteResponse, err error)
	// ListNotes 查询用户笔记列表（直查 MongoDB，依赖 user_id+created_at 复合索引）
	ListNotes(ctx context.Context, req *ListNotesRequest, opts ...client.Option) (rsp *ListNotesResponse, err error)
	// DeleteNote 删除笔记（先删 Mongo 再 Del Redis 缓存）
	DeleteNote(ctx context.Context, req *DeleteNoteRequest, opts ...client.Option) (rsp *DeleteNoteResponse, err error)
}

type NoteServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewNoteServiceClientProxy = func(opts ...client.Option) NoteServiceClientProxy {
	return &NoteServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *NoteServiceClientProxyImpl) CreateNote(ctx context.Context, req *CreateNoteRequest, opts ...client.Option) (*CreateNoteResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.demo.note.NoteService/CreateNote")
	msg.WithCalleeServiceName(NoteServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("demo")
	msg.WithCalleeServer("note")
	msg.WithCalleeService("NoteService")
	msg.WithCalleeMethod("CreateNote")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateNoteResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *NoteServiceClientProxyImpl) GetNote(ctx context.Context, req *GetNoteRequest, opts ...client.Option) (*GetNoteResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.demo.note.NoteService/GetNote")
	msg.WithCalleeServiceName(NoteServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("demo")
	msg.WithCalleeServer("note")
	msg.WithCalleeService("NoteService")
	msg.WithCalleeMethod("GetNote")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetNoteResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *NoteServiceClientProxyImpl) ListNotes(ctx context.Context, req *ListNotesRequest, opts ...client.Option) (*ListNotesResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.demo.note.NoteService/ListNotes")
	msg.WithCalleeServiceName(NoteServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("demo")
	msg.WithCalleeServer("note")
	msg.WithCalleeService("NoteService")
	msg.WithCalleeMethod("ListNotes")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListNotesResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *NoteServiceClientProxyImpl) DeleteNote(ctx context.Context, req *DeleteNoteRequest, opts ...client.Option) (*DeleteNoteResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.demo.note.NoteService/DeleteNote")
	msg.WithCalleeServiceName(NoteServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("demo")
	msg.WithCalleeServer("note")
	msg.WithCalleeService("NoteService")
	msg.WithCalleeMethod("DeleteNote")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DeleteNoteResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
