// Code generated by MockGen. DO NOT EDIT.
// Source: stub/git.woa.com/trpcprotocol/demo/note/note.trpc.go
//
// Generated by this command:
//
//	mockgen -destination=stub/git.woa.com/trpcprotocol/demo/note/note_mock.go -package=note -self_package=git.woa.com/trpcprotocol/demo/note --source=stub/git.woa.com/trpcprotocol/demo/note/note.trpc.go
//

// Package note is a generated GoMock package.
package note

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockNoteServiceService is a mock of NoteServiceService interface.
type MockNoteServiceService struct {
	ctrl     *gomock.Controller
	recorder *MockNoteServiceServiceMockRecorder
}

// MockNoteServiceServiceMockRecorder is the mock recorder for MockNoteServiceService.
type MockNoteServiceServiceMockRecorder struct {
	mock *MockNoteServiceService
}

// NewMockNoteServiceService creates a new mock instance.
func NewMockNoteServiceService(ctrl *gomock.Controller) *MockNoteServiceService {
	mock := &MockNoteServiceService{ctrl: ctrl}
	mock.recorder = &MockNoteServiceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteServiceService) EXPECT() *MockNoteServiceServiceMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockNoteServiceService) ISGOMOCK() struct{} {
	return struct{}{}
}

// CreateNote mocks base method.
func (m *MockNoteServiceService) CreateNote(ctx context.Context, req *CreateNoteRequest) (*CreateNoteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, req)
	ret0, _ := ret[0].(*CreateNoteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockNoteServiceServiceMockRecorder) CreateNote(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockNoteServiceService)(nil).CreateNote), ctx, req)
}

// DeleteNote mocks base method.
func (m *MockNoteServiceService) DeleteNote(ctx context.Context, req *DeleteNoteRequest) (*DeleteNoteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNote", ctx, req)
	ret0, _ := ret[0].(*DeleteNoteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockNoteServiceServiceMockRecorder) DeleteNote(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockNoteServiceService)(nil).DeleteNote), ctx, req)
}

// GetNote mocks base method.
func (m *MockNoteServiceService) GetNote(ctx context.Context, req *GetNoteRequest) (*GetNoteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNote", ctx, req)
	ret0, _ := ret[0].(*GetNoteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNote indicates an expected call of GetNote.
func (mr *MockNoteServiceServiceMockRecorder) GetNote(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNote", reflect.TypeOf((*MockNoteServiceService)(nil).GetNote), ctx, req)
}

// ListNotes mocks base method.
func (m *MockNoteServiceService) ListNotes(ctx context.Context, req *ListNotesRequest) (*ListNotesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotes", ctx, req)
	ret0, _ := ret[0].(*ListNotesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotes indicates an expected call of ListNotes.
func (mr *MockNoteServiceServiceMockRecorder) ListNotes(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotes", reflect.TypeOf((*MockNoteServiceService)(nil).ListNotes), ctx, req)
}

// MockNoteServiceClientProxy is a mock of NoteServiceClientProxy interface.
type MockNoteServiceClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockNoteServiceClientProxyMockRecorder
}

// MockNoteServiceClientProxyMockRecorder is the mock recorder for MockNoteServiceClientProxy.
type MockNoteServiceClientProxyMockRecorder struct {
	mock *MockNoteServiceClientProxy
}

// NewMockNoteServiceClientProxy creates a new mock instance.
func NewMockNoteServiceClientProxy(ctrl *gomock.Controller) *MockNoteServiceClientProxy {
	mock := &MockNoteServiceClientProxy{ctrl: ctrl}
	mock.recorder = &MockNoteServiceClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteServiceClientProxy) EXPECT() *MockNoteServiceClientProxyMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockNoteServiceClientProxy) ISGOMOCK() struct{} {
	return struct{}{}
}

// CreateNote mocks base method.
func (m *MockNoteServiceClientProxy) CreateNote(ctx context.Context, req *CreateNoteRequest, opts ...client.Option) (*CreateNoteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateNote", varargs...)
	ret0, _ := ret[0].(*CreateNoteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockNoteServiceClientProxyMockRecorder) CreateNote(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockNoteServiceClientProxy)(nil).CreateNote), varargs...)
}

// DeleteNote mocks base method.
func (m *MockNoteServiceClientProxy) DeleteNote(ctx context.Context, req *DeleteNoteRequest, opts ...client.Option) (*DeleteNoteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteNote", varargs...)
	ret0, _ := ret[0].(*DeleteNoteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockNoteServiceClientProxyMockRecorder) DeleteNote(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockNoteServiceClientProxy)(nil).DeleteNote), varargs...)
}

// GetNote mocks base method.
func (m *MockNoteServiceClientProxy) GetNote(ctx context.Context, req *GetNoteRequest, opts ...client.Option) (*GetNoteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetNote", varargs...)
	ret0, _ := ret[0].(*GetNoteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNote indicates an expected call of GetNote.
func (mr *MockNoteServiceClientProxyMockRecorder) GetNote(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNote", reflect.TypeOf((*MockNoteServiceClientProxy)(nil).GetNote), varargs...)
}

// ListNotes mocks base method.
func (m *MockNoteServiceClientProxy) ListNotes(ctx context.Context, req *ListNotesRequest, opts ...client.Option) (*ListNotesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListNotes", varargs...)
	ret0, _ := ret[0].(*ListNotesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotes indicates an expected call of ListNotes.
func (mr *MockNoteServiceClientProxyMockRecorder) ListNotes(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotes", reflect.TypeOf((*MockNoteServiceClientProxy)(nil).ListNotes), varargs...)
}
