// Package main is originally generated by trpc-cmdline v1.0.9.
// It is located at `project/cmd/client`.
// Run this file by executing `go run cmd/client/main.go` in the project directory.
package main

import (
	pb "git.woa.com/trpcprotocol/demo/note"
	_ "trpc.group/trpc-go/trpc-filter/debuglog"
	trpc "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/log"
)

func callNoteServiceCreateNote() {
	proxy := pb.NewNoteServiceClientProxy(
		client.WithTarget("ip://127.0.0.1:8000"),
		client.WithProtocol("trpc"),
	)
	ctx := trpc.BackgroundContext()
	// Example usage of unary client.
	reply, err := proxy.CreateNote(ctx, &pb.CreateNoteRequest{})
	if err != nil {
		log.Fatalf("err: %v", err)
	}
	log.Debugf("simple  rpc   receive: %+v", reply)
}

func callNoteServiceGetNote() {
	proxy := pb.NewNoteServiceClientProxy(
		client.WithTarget("ip://127.0.0.1:8000"),
		client.WithProtocol("trpc"),
	)
	ctx := trpc.BackgroundContext()
	// Example usage of unary client.
	reply, err := proxy.GetNote(ctx, &pb.GetNoteRequest{})
	if err != nil {
		log.Fatalf("err: %v", err)
	}
	log.Debugf("simple  rpc   receive: %+v", reply)
}

func callNoteServiceListNotes() {
	proxy := pb.NewNoteServiceClientProxy(
		client.WithTarget("ip://127.0.0.1:8000"),
		client.WithProtocol("trpc"),
	)
	ctx := trpc.BackgroundContext()
	// Example usage of unary client.
	reply, err := proxy.ListNotes(ctx, &pb.ListNotesRequest{})
	if err != nil {
		log.Fatalf("err: %v", err)
	}
	log.Debugf("simple  rpc   receive: %+v", reply)
}

func callNoteServiceDeleteNote() {
	proxy := pb.NewNoteServiceClientProxy(
		client.WithTarget("ip://127.0.0.1:8000"),
		client.WithProtocol("trpc"),
	)
	ctx := trpc.BackgroundContext()
	// Example usage of unary client.
	reply, err := proxy.DeleteNote(ctx, &pb.DeleteNoteRequest{})
	if err != nil {
		log.Fatalf("err: %v", err)
	}
	log.Debugf("simple  rpc   receive: %+v", reply)
}

func callNoteServiceUpdateNote() {
	proxy := pb.NewNoteServiceClientProxy(
		client.WithTarget("ip://127.0.0.1:8000"),
		client.WithProtocol("trpc"),
	)
	ctx := trpc.BackgroundContext()
	reply, err := proxy.UpdateNote(ctx, &pb.UpdateNoteRequest{
		NoteId:          "your_note_id",
		UserId:          "your_user_id",
		Title:           "updated title",
		Content:         "updated content",
		ExpectedVersion: 1,
	})
	if err != nil {
		log.Fatalf("err: %v", err)
	}
	log.Debugf("UpdateNote receive: %+v", reply)
}

func callNoteServiceListNoteVersions() {
	proxy := pb.NewNoteServiceClientProxy(
		client.WithTarget("ip://127.0.0.1:8000"),
		client.WithProtocol("trpc"),
	)
	ctx := trpc.BackgroundContext()
	reply, err := proxy.ListNoteVersions(ctx, &pb.ListNoteVersionsRequest{
		NoteId:   "your_note_id",
		UserId:   "your_user_id",
		Page:     1,
		PageSize: 20,
	})
	if err != nil {
		log.Fatalf("err: %v", err)
	}
	log.Debugf("ListNoteVersions receive: %+v", reply)
}

func callNoteServiceRestoreNoteVersion() {
	proxy := pb.NewNoteServiceClientProxy(
		client.WithTarget("ip://127.0.0.1:8000"),
		client.WithProtocol("trpc"),
	)
	ctx := trpc.BackgroundContext()
	reply, err := proxy.RestoreNoteVersion(ctx, &pb.RestoreNoteVersionRequest{
		NoteId:          "your_note_id",
		UserId:          "your_user_id",
		Version:         2,
		ExpectedVersion: 5,
	})
	if err != nil {
		log.Fatalf("err: %v", err)
	}
	log.Debugf("RestoreNoteVersion receive: %+v", reply)
}

func main() {
	// Load configuration following the logic in trpc.NewServer.
	cfg, err := trpc.LoadConfig(trpc.ServerConfigPath)
	if err != nil {
		panic("load config fail: " + err.Error())
	}
	trpc.SetGlobalConfig(cfg)
	if err := trpc.Setup(cfg); err != nil {
		panic("setup plugin fail: " + err.Error())
	}
	callNoteServiceCreateNote()
	callNoteServiceGetNote()
	callNoteServiceListNotes()
	callNoteServiceDeleteNote()
	callNoteServiceUpdateNote()
	callNoteServiceListNoteVersions()
	callNoteServiceRestoreNoteVersion()
}
